name: OHW20
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pangeo-notebook=2020.06.03
  - argopy
  - bokeh
  - cartopy
  - cdsapi
  - cf-units
  - colorcet
  - compilers
  - ctd
  - datashader
  - erddapy
  - geolinks
  - geopandas
  - geoviews
  - gsw
  - holoviews
  - hvplot
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - jupyter_contrib_nbextensions
  - jupyterlab
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numpy
  - palettable
  - pandas
  - panel
  - param
  - podaacpy
  - pyoos
  - rasterio
  - requests
  - retrying
  - seaborn
  - shapely
  - siphon
  - xarray
  - xlrd
  # R packages
  - r-base
  - r-ape
  - r-cowplot
  - r-crul
  - r-gridextra
  - r-gsw
  - r-irkernel
  - r-leaflet
  - r-mapdata
  - r-maps
  - r-maptools
  - r-ncdf4
  - r-oce
  - r-patchwork
  - r-plotly
  - r-raster
  - r-rastervis
  - r-remotes
  - r-rgdal
  - r-rgeos
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-sf
  - r-tidyverse
  - r-vegan
  - rpy2
  # robis deps
  - r-commonmark
  - r-httr
  - r-dplyr
  - r-jsonlite
  - r-leaflet
  - r-ggplot2
  - r-tidyr
  - r-httpcache
  - r-tibble
  - r-mapedit
  - r-sf
  - r-rlang
  # extras
  - conda-lock
  - emacs
  - git
  - graphviz
  - unzip
  - vim
  - zip
