name: OHW20
channels:
  - conda-forge
dependencies:
  - python=3.8
  - altair
  - basemap
  - bokeh
  - boto3
  - cartopy
  - cc-plugin-ncei
  - ciso
  - cmocean
  - colorcet
  - compliance-checker
  - datashader
  - descartes
  - erddapy
  - folium
  - geolinks
  - geopandas
  - geoviews
  - gridgeo
  - holoviews
  - hvplot
  - ioos-tools
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - jupyter_contrib_nbextensions
  - matplotlib
  - netcdf4
  - numpy
  - owslib
  - palettable
  - pandas
  - panel
  - param
  - pocean-core
  - podaacpy
  - pyoos
  - rasterio
  - requests
  - retrying
  - rise
  - seaborn
  - shapely
  - sympy
  - unyt
  - utide
  - vega_datasets
  - xarray
  - xlrd
  # R packages
  - r-base
  - rpy2
  - r-tidyverse
